/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-03-29 09:27:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"Ogani Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"Ogani, unica, creative, html\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Ogani | Template</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Humberger End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Header Section Begin -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"header__top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"header__top__left\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><i class=\"fa fa-envelope\"></i> hello@colorlib.com</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"header__top__right\">\r\n");
      out.write("                            <div class=\"header__top__right__social\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-pinterest-p\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"header__top__right__auth\">\r\n");
      out.write("                                <a href=\"signup.jsp\"><i class=\"fa fa-user\"></i> Sign Up</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"header__top__right__auth\">\r\n");
      out.write("                                <a href=\"login.jsp\"><i class=\"fa fa-user\"></i> Login</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3\">\r\n");
      out.write("                    <div class=\"header__logo\">\r\n");
      out.write("                        <a href=\"./index.html\"><img src=\"img/logo.png\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <nav class=\"header__menu\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"./index.html\">Home</a></li>\r\n");
      out.write("                            <li class=\"active\"><a href=\"./shop-grid.html\">Shop</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Pages</a>\r\n");
      out.write("                                <ul class=\"header__menu__dropdown\">\r\n");
      out.write("                                    <li><a href=\"./shop-details.html\">Shop Details</a></li>\r\n");
      out.write("                                    <li><a href=\"./shoping-cart.html\">Shoping Cart</a></li>\r\n");
      out.write("                                    <li><a href=\"./checkout.html\">Check Out</a></li>\r\n");
      out.write("                                    <li><a href=\"./blog-details.html\">Blog Details</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"./blog.html\">Blog</a></li>\r\n");
      out.write("                            <li><a href=\"./contact.html\">Contact</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3\">\r\n");
      out.write("                    <div class=\"header__cart\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-heart\"></i> <span>1</span></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-shopping-bag\"></i> <span>3</span></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"header__cart__price\">item: <span>$150.00</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"humberger__open\">\r\n");
      out.write("                <i class=\"fa fa-bars\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Hero Section Begin -->\r\n");
      out.write("    <section class=\"hero hero-normal\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3\">\r\n");
      out.write("                    <div class=\"hero__categories\">\r\n");
      out.write("                        <div class=\"hero__categories__all\">\r\n");
      out.write("                            <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                            <span>All departments</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Fresh Meat</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Vegetables</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Fruit & Nut Gifts</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Fresh Berries</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Ocean Foods</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Butter & Eggs</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Fastfood</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Fresh Onion</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Papayaya & Crisps</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Oatmeal</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Fresh Bananas</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-9\">\r\n");
      out.write("                    <div class=\"hero__search\">\r\n");
      out.write("                        <div class=\"hero__search__form\">\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <div class=\"hero__search__categories\">\r\n");
      out.write("                                    All Categories\r\n");
      out.write("                                    <span class=\"arrow_carrot-down\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <input type=\"text\" placeholder=\"What do yo u need?\">\r\n");
      out.write("                                <button type=\"submit\" class=\"site-btn\">SEARCH</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hero__search__phone\">\r\n");
      out.write("                            <div class=\"hero__search__phone__icon\">\r\n");
      out.write("                                <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"hero__search__phone__text\">\r\n");
      out.write("                                <h5>+65 11.188.888</h5>\r\n");
      out.write("                                <span>support 24/7 time</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Hero Section End -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
